<a href="https://colab.research.google.com/github/stevensmiley1989/data-science-ipython-notebooks/blob/master/simple_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
def row_echelon(A):
    """ Return Row Echelon Form of matrix A """

    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]
    return A 

In [2]:
print('############################')
#Creating a matrix A
A = np.array([[2,43,123,4],[1,4,4,2],[2,7,3,9],[3,8,3,4]])
#A=row_echelon(A)
print('A=',A)
#Performing SVD
U, D, VT = np.linalg.svd(A)
 
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(D) @ VT)
print('A_remake = (U@np.diag(D)@VT)',A_remake)
A_also_remake=np.dot(np.dot(U,np.diag(D)),VT)

############################
A= [[  2  43 123   4]
 [  1   4   4   2]
 [  2   7   3   9]
 [  3   8   3   4]]
A_remake = (U@np.diag(D)@VT) [[  2.  43. 123.   4.]
 [  1.   4.   4.   2.]
 [  2.   7.   3.   9.]
 [  3.   8.   3.   4.]]


In [3]:
#get covariance matrix of x
cm=np.zeros(shape=A.shape)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        cm[i,j]=np.dot(A[i]-np.mean(A[i]),(A[j]-np.mean(A[j])))/2
print('###############################')
print('Covariance Matrix of A by hand')
print(cm)
print('np.cov(A)')
print(np.cov(A))
print(' ')

###############################
Covariance Matrix of A by hand
[[ 4.8010e+03  1.0050e+02 -9.6500e+01 -1.9500e+01]
 [ 1.0050e+02  3.3750e+00  1.1250e+00  2.7500e+00]
 [-9.6500e+01  1.1250e+00  1.6375e+01  6.2500e+00]
 [-1.9500e+01  2.7500e+00  6.2500e+00  8.5000e+00]]
np.cov(A)
[[ 3.20066667e+03  6.70000000e+01 -6.43333333e+01 -1.30000000e+01]
 [ 6.70000000e+01  2.25000000e+00  7.50000000e-01  1.83333333e+00]
 [-6.43333333e+01  7.50000000e-01  1.09166667e+01  4.16666667e+00]
 [-1.30000000e+01  1.83333333e+00  4.16666667e+00  5.66666667e+00]]
 


In [4]:
from sklearn.decomposition import PCA
pca=PCA()
cA_pca=pca.fit_transform(np.cov(A))
print('#############################')
print('PCA of np.cov(A)')
print(cA_pca)
print('pca.n_components_=',pca.n_components_)
tot = sum(pca.explained_variance_)
print('sum(pca.explained_variance_)',tot)
var_exp = [(i/tot)*100 for i in sorted(pca.explained_variance_, reverse=True)]
print('var_exp',var_exp)
# Cumulative explained variance
cum_var_exp = np.cumsum(var_exp)
print('cum_var_exp = np.cumsum(var_exp)',cum_var_exp)
componentsVariance = [A.shape[0]*A.shape[1], np.argmax(cum_var_exp > 99) + 1, np.argmax(cum_var_exp > 95) + 1]
print('componentsVariance',componentsVariance)
print(' ')

pca=PCA()
A_pca=pca.fit_transform(A)
print('#############################')
print('PCA of A')
print(A_pca)
print('pca.n_components_=',pca.n_components_)
tot = sum(pca.explained_variance_)
print('sum(pca.explained_variance_)',tot)
var_exp = [(i/tot)*100 for i in sorted(pca.explained_variance_, reverse=True)]
print('var_exp',var_exp)
# Cumulative explained variance
cum_var_exp = np.cumsum(var_exp)
print('cum_var_exp = np.cumsum(var_exp)',cum_var_exp)
componentsVariance = [A.shape[0]*A.shape[1], np.argmax(cum_var_exp > 99) + 1, np.argmax(cum_var_exp > 95) + 1]
print('componentsVariance',componentsVariance)
print(' ')

#############################
PCA of np.cov(A)
[[ 2.40418400e+03  1.49907988e-01  2.53502615e-02  2.75253187e-15]
 [-7.30860071e+02 -3.29325607e+00 -1.38895946e+00  2.75253187e-15]
 [-8.62397423e+02  4.24106451e+00 -5.77124851e-01  2.75253187e-15]
 [-8.10926509e+02 -1.09771643e+00  1.94073405e+00  2.75253187e-15]]
pca.n_components_= 4
sum(pca.explained_variance_) 2571874.791666667
var_exp [99.99953226092224, 0.00038959410219509315, 7.814497557073019e-05, 3.927838533899075e-34]
cum_var_exp = np.cumsum(var_exp) [ 99.99953226  99.99992186 100.         100.        ]
componentsVariance [16, 1, 1]
 
#############################
PCA of A
[[ 9.38715876e+01  4.36389513e-03 -4.63691185e-03  6.88919606e-16]
 [-3.13126019e+01 -3.81878831e+00 -1.14578399e+00  6.88919606e-16]
 [-3.14461179e+01  3.92546377e+00 -1.05233271e+00  6.88919606e-16]
 [-3.11128679e+01 -1.11039356e-01  2.20275361e+00  6.88919606e-16]]
pca.n_components_= 4
sum(pca.explained_variance_) 3928.833333333334
var_exp [99.68373029481

In [5]:
print('##############A###############')
print('eigenvalues from np.linalg.svd')
print(sorted(np.linalg.svd(A)[1]**2)) #eigenvalues from np.linalg.svd
print('eigenvalues from np.linalg.eig')
print(sorted(np.linalg.eig(np.dot(A.T,A))[0])) #eigenvalues from np.linalg.eig
print('Pretty close, but not the exact same')
print('##############np.cov(A)################')
print('eigenvalues from np.linalg.svd')
print(sorted(np.linalg.svd(np.cov(A))[1]**2)) #eigenvalues from np.linalg.svd
print('eigenvalues from np.linalg.eig')
print(sorted(np.linalg.eig(np.dot(np.cov(A).T,np.cov(A)))[0])) #eigenvalues from np.linalg.eig
print('Pretty close, but not the exact same')

##############A###############
eigenvalues from np.linalg.svd
[0.011673063578790787, 10.266508889336107, 178.7466547221083, 17086.97516332499]
eigenvalues from np.linalg.eig
[0.01167306357877594, 10.26650888933635, 178.74665472210862, 17086.97516332498]
Pretty close, but not the exact same
##############np.cov(A)################
eigenvalues from np.linalg.svd
[9.294989728103415e-32, 11.359655639766883, 161.58552070611034, 10261886.638156988]
eigenvalues from np.linalg.eig
[3.110936925435891e-12, 11.359655639767775, 161.58552070611128, 10261886.638156984]
Pretty close, but not the exact same


In [6]:
print('##############################')
print('prove (A-eig_v)*eig_vec=0')
print('A',A)
eig_values_A=np.linalg.eig(np.dot(A.T,A))[0]
print('eig_values_A',sorted(eig_values_A))
eig_vectors_A=np.linalg.eig(np.dot(A.T,A))[1]
print('eig_vectors_A',eig_vectors_A)
result=np.sum((np.dot(A.T,A)-np.diag(eig_values_A))*eig_vectors_A.T)
print(result)
print('np.sum((A-np.diag(eig_values_A))*eig_vectors_A.T) =',np.round(np.sqrt(result.real**2+result.imag**2),4))


##############################
prove (A-eig_v)*eig_vec=0
A [[  2  43 123   4]
 [  1   4   4   2]
 [  2   7   3   9]
 [  3   8   3   4]]
eig_values_A [0.01167306357877594, 10.26650888933635, 178.74665472210862, 17086.97516332498]
eig_vectors_A [[ 0.01720893  0.25352886  0.89165576 -0.37466915]
 [ 0.33422959  0.60637723 -0.42413342 -0.58370204]
 [ 0.94167068 -0.24660384  0.13090025  0.18790422]
 [ 0.03536611  0.7121912   0.0890279   0.69541855]]
2.7284841053187847e-12
np.sum((A-np.diag(eig_values_A))*eig_vectors_A.T) = 0.0
